import configparser
import os

class Config:
    
    def __init__(self):
        if not os.path.exists('config.ini'):
            self.create_config()
        self.file = configparser.ConfigParser()
        self.file.read('config.ini')

    def get(self, section, param):
        return self.file.get(section, param)

    def create_config(self):
        new = configparser.ConfigParser()
        new.add_section('FTP')
        new.set('FTP', 'host', '127.0.0.1')
        new.set('FTP', 'user', '')
        new.set('FTP', 'pswd', '')
        new.set('FTP', 'dir', '')
        new.add_section('REDIS')
        new.set('REDIS', 'host', '127.0.0.1')
        new.set('REDIS', 'port', '')
        new.set('REDIS', 'pswd', '')
        new.set('REDIS', 'dir', '')
        new.add_section('MACS LIST')
        new.set('MACS LIST', 'lifetime', '7')
        new.add_section('CABINET SQL')
        new.set('CABINET SQL', 'host', '127.0.0.1')
        new.set('CABINET SQL', 'port', '3306')
        new.set('CABINET SQL', 'user', 'root')
        new.set('CABINET SQL', 'pswd', 'admin')
        new.set('CABINET SQL', 'db', 'cabinet')
        new.add_section('STORAGE SQL')
        new.set('STORAGE SQL', 'host', '127.0.0.1')
        new.set('STORAGE SQL', 'port', '3306')
        new.set('STORAGE SQL', 'user', 'root')
        new.set('STORAGE SQL', 'pswd', 'admin')
        new.set('STORAGE SQL', 'db', 'storage')
        new.add_section('FILES')
        new.set('FILES', 'size_limit', '200')
        new.set('FILES', 'check_time', '3')
        new.add_section('OLD FILES')
        new.set('OLD FILES', 'archive', 'True')
        new.set('OLD FILES', 'processes', '1')
        new.set('OLD FILES', 'path', 'ftp/old/')
        new.set('OLD FILES', 'overload', 'False')
        new.set('OLD FILES', 'overload_threshold', '100')
        new.set('OLD FILES', 'log_level', 'INFO')
        new.add_section('MOBILE FILES')
        new.set('MOBILE FILES', 'archive', 'True')
        new.set('MOBILE FILES', 'processes', '1')
        new.set('MOBILE FILES', 'path', 'ftp/mobile/')
        new.set('MOBILE FILES', 'overload', 'False')
        new.set('MOBILE FILES', 'overload_threshold', '50')
        new.set('MOBILE FILES', 'log_level', 'INFO')
        new.add_section('SIMPLE FILES')
        new.set('SIMPLE FILES', 'archive', 'True')
        new.set('SIMPLE FILES', 'processes', '3')
        new.set('SIMPLE FILES', 'path', 'ftp/simple/')
        new.set('SIMPLE FILES', 'overload', 'True')
        new.set('SIMPLE FILES', 'overload_threshold', '50')
        new.set('SIMPLE FILES', 'log_level', 'INFO')
        new.add_section('GOF FILES')
        new.set('GOF FILES', 'archive', 'True')
        new.set('GOF FILES', 'processes', '1')
        new.set('GOF FILES', 'path', 'ftp/gof/')
        new.set('GOF FILES', 'overload', 'False')
        new.set('GOF FILES', 'overload_threshold', '150')
        new.set('GOF FILES', 'log_level', 'INFO')

        with open('config.ini', 'w') as config_file:
            new.write(config_file)